### ISSUE TITLE
Complaints with Django bouncy not working! 

### ISSUE THREAD

**Issue by hubert10** [ofa/django-bouncy#25]
Hello,
I followed step by step the following link [django bouncy](https://github.com/ofa/django-bouncy) to configure bouncy with my Django application and everything seems to work fine (Bouncy and Delivery messages are well logged), but my issue is for **Complaints**. When an email address _is marked as spam Django bouncy still processes email delivery_. Does anyone have an idea  on what is going on? or Is there any further config  I should add to those provided by [django bouncy](https://github.com/ofa/django-bouncy).

Thank you!!!

**Comment by subramanyamVemu** [comment]
HI

From a email delivery point of view the email is first delivered and only
then it's marked as spam
So its very much valid

In order to not show the complained emails your application code should be
handling the scenario based on the type of the signal received in you
signal_handler.py

Thanks
Bala
